[project]
name = "JR"
version = "0.1"
requires-python = ">=3.13.0"
dependencies = [
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "aiosqlite>=0.17.0",
    "pydantic>=2.0.0",
    "requests>=2.32.4",
    "httpx",
    "openai>=2.1.0",
    "dotenv>=0.9.9",
]
